### ISSUE TITLE
Verallgemeinern der CSV Auslesung

### ISSUE THREAD

**Issue by VakuumimKopf** [VakuumimKopf/SoEnt-Project#23]
Momentan werden alle CSV Dateien nach ";" getrennt, es soll aber allgemein für ein beliebiges Trennzeichen funktionieren. 
Außerdem sollte die GetTabelHead Funktion im Reader Interface allgemein keinen String ausgeben, sondern ein Array mit allen Head Elementen als String um so nicht noch mal extern den String aufteilen zu müssen. Es müssen also auch alle Stellen wo diese Funktion aufgerufen wird verändert werden.

**Comment by FelixK09** [comment]
Wegen der Komplexität des Programms wird des ';' das einzige Trennzeichen bleiben. Sollte man Programm später noch erweitern wollen ist dies ein Sache die man noch umsetzen könnte.
